Repository st-tiendinh/FE-Internship-2023_Litit-Blog_Final-Project, pull requests merged in 2023-09, with the labels that each got.

#1 [Task] - Add Stylesheet Base
  src/stylesheet/base/_all.scss
  src/stylesheet/base/_base.scss
  src/stylesheet/base/_reset.scss
  src/stylesheet/base/_variables.scss
  src/stylesheet/layout/_all.scss
  src/stylesheet/layout/_grid.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_badge.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_skeleton.scss
  src/stylesheet/modules/_spinner.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/states/_all.scss
  src/stylesheet/states/_state.scss
  src/stylesheet/style.scss
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Task

#3 [Task] Create post component
  package-lock.json
  package.json
  src/App.tsx
  src/app/assets/post-img.jpg
  src/app/assets/react.svg
  src/app/shared/components/Post.tsx
  src/stylesheet/base/_base.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_badge.scss
  src/stylesheet/modules/_button.scss
  src/stylesheet/modules/_post.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Task

#4 [Initial Base] Config router paths
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/AppSuspense.tsx
  src/app/app.route.ts
  src/app/core/auth/Auth.tsx
  src/app/core/auth/auth.routes.ts
  src/app/core/auth/containers/Login.tsx
  src/app/core/auth/containers/Register.tsx
  src/app/core/modules/custom-router-dom/PrivateRoute.tsx
  src/app/core/modules/custom-router-dom/RouterOutlet.tsx
  src/app/core/modules/custom-router-dom/index.ts
  src/app/core/modules/custom-router-dom/router.interface.ts
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#2 Add Header UI
  .gitignore
  package-lock.json
  package.json
  src/assets/images/logo.png
  src/shared/components/Header.tsx
  src/shared/components/index.tsx
  src/stylesheet/base/_reset.scss
  src/stylesheet/layout/_all.scss
  src/stylesheet/layout/_header.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_button.scss
  src/stylesheet/modules/_icon.scss
Labels: [Priority] 03 - Low, [Status] 03 - Review needed, [Type] Task

#5 [Task] - Add component input
  src/shared/components/InputField.tsx
  src/stylesheet/base/_reset.scss
  src/stylesheet/base/_variables.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_input-field.scss
Labels: [Priority] 03 - Low, [Status] 03 - Review needed, [Type] Task

#11 [Setup API Service] Setup api services
  .eslintrc.cjs
  package-lock.json
  package.json
  src/app/core/helpers/authHelper.ts
  src/app/core/helpers/jwtHelper.ts
  src/app/core/helpers/storageHelper.ts
  src/app/core/services/api.service.ts
  src/app/core/services/authStorage.service.ts
  src/config/endpoint.ts
  src/config/environment.ts
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#6 [Task] Create footer
  src/App.tsx
  src/app/shared/components/Footer.tsx
  src/assets/images/logo.png
  src/stylesheet/base/_reset.scss
  src/stylesheet/layout/_all.scss
  src/stylesheet/layout/_footer.scss
Labels: [Priority] 03 - Low, [Status] 03 - Review needed, [Type] Feature

#12 [Initial setup] Create base source
  .eslintrc.cjs
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/AppSuspense.tsx
  src/app/app.route.ts
  src/app/core/auth/Auth.tsx
  src/app/core/auth/auth.routes.ts
  src/app/core/auth/containers/Login.tsx
  src/app/core/auth/containers/Register.tsx
  src/app/core/helpers/authHelper.ts
  src/app/core/helpers/jwtHelper.ts
  src/app/core/helpers/storageHelper.ts
  src/app/core/modules/custom-router-dom/PrivateRoute.tsx
  src/app/core/modules/custom-router-dom/RouterOutlet.tsx
  src/app/core/modules/custom-router-dom/index.ts
  src/app/core/modules/custom-router-dom/router.interface.ts
  src/app/core/services/api.service.ts
  src/app/core/services/authStorage.service.ts
  src/app/shared/components/Footer.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/InputField.tsx
  src/assets/images/logo.png
  src/config/endpoint.ts
  src/config/environment.ts
  src/stylesheet/base/_reset.scss
  src/stylesheet/base/_variables.scss
  src/stylesheet/layout/_all.scss
  src/stylesheet/layout/_footer.scss
  src/stylesheet/layout/_header.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_button.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_input-field.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#15 [Task] Add post list
  src/app/pages/home/index.tsx
  src/app/shared/components/PostList.tsx
  src/stylesheet/layout/_header.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/pages/_home.scss
Labels: [Priority] 03 - Low, [Status] 03 - Review needed, [Type] Task

#16 [Task] - Create register UI
  src/app/core/auth/Auth.tsx
  src/app/core/auth/containers/Register.tsx
  src/app/shared/components/InputGroup.tsx
  src/assets/icons/ic-hide.svg
  src/assets/icons/ic-show.svg
  src/assets/images/register-cover.png
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_input-group.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/pages/_register.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Task

#21 [Feature] Handle error and loading for login
  src/app/core/auth/auth.reducers.ts
  src/app/core/auth/containers/Login.tsx
  src/app/core/helpers/jwtHelper.ts
  src/config/endpoint.ts
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#20 [Task] - Validate for login form
  package-lock.json
  package.json
  src/app/core/auth/containers/Login.tsx
  src/app/shared/components/InputGroup.tsx
  src/stylesheet/base/_variables.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Task

#19 [Feature] Apply API login
  package-lock.json
  package.json
  src/App.tsx
  src/app/app.middleware.ts
  src/app/app.reducers.ts
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.middleware.ts
  src/app/core/auth/auth.reducers.ts
  src/app/core/auth/constants/types.ts
  src/app/core/auth/containers/Login.tsx
  src/app/core/helpers/authHelper.ts
  src/app/core/helpers/jwtHelper.ts
  src/app/core/helpers/reducer-factory.ts
  src/app/core/services/api.service.ts
  src/app/core/services/auth.service.ts
  src/config/endpoint.ts
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#23 [Feature] Config router for pages
  src/App.tsx
  src/app/app.route.ts
  src/app/pages/Page.tsx
  src/app/pages/articles/article.routes.ts
  src/app/pages/articles/containers/ArticleDetail.tsx
  src/app/pages/articles/containers/ArticleList.tsx
  src/app/pages/articles/containers/Articles.tsx
  src/app/pages/home/containers/Home.tsx
  src/app/pages/home/home.routes.ts
  src/app/pages/page.routes.ts
  src/app/pages/user/containers/UserDetail.tsx
  src/app/pages/user/containers/UserList.tsx
  src/app/pages/user/containers/Users.tsx
  src/app/pages/user/user.routes.ts
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#24 [Feature] Modify header link and file import
  src/App.tsx
  src/app/shared/components/Footer.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/index.tsx
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Feature

#22 [Task] Apply API to get latest public post
  package-lock.json
  src/App.tsx
  src/app/app.route.ts
  src/app/pages/Page.tsx
  src/app/pages/articles/article.routes.ts
  src/app/pages/articles/containers/ArticleDetail.tsx
  src/app/pages/articles/containers/ArticleList.tsx
  src/app/pages/articles/containers/Articles.tsx
  src/app/pages/home/components/PublicPost.tsx
  src/app/pages/home/containers/Home.tsx
  src/app/pages/home/home.routes.ts
  src/app/pages/home/index.tsx
  src/app/pages/page.routes.ts
  src/app/pages/user/containers/UserDetail.tsx
  src/app/pages/user/containers/UserList.tsx
  src/app/pages/user/containers/Users.tsx
  src/app/pages/user/user.routes.ts
  src/app/shared/components/Post.tsx
  src/app/shared/components/PostList.tsx
  src/app/shared/utils/checkValidImage.ts
  src/app/shared/utils/formatDate.ts
  src/assets/icons/ic-comment.svg
  src/assets/icons/ic-unlike.svg
  src/assets/images/blank-post.png
  src/assets/images/blank-user.webp
  src/config/endpoint.ts
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_post.scss
  src/stylesheet/pages/_home.scss
  src/stylesheet/states/_state.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#25 [Feature] - Apply api register
  src/app/core/auth/containers/Register.tsx
  src/config/endpoint.ts
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Feature

#27 [Feature] - Add Load more button for List post
  src/app/pages/home/containers/components/PublicPost.tsx
  src/app/pages/home/containers/components/ScrollToTopButton.tsx
  src/assets/icons/ic-arrow-up.svg
  src/config/endpoint.ts
  src/stylesheet/modules/_icon.scss
  src/stylesheet/pages/_home.scss
  src/stylesheet/states/_state.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Feature

#28 [Feature] Add loadding and errror UI
  src/app/core/auth/auth.reducers.ts
  src/app/core/auth/containers/Login.tsx
  src/app/core/helpers/authHelper.ts
  src/app/shared/components/Spinner.tsx
  src/app/shared/components/index.tsx
  src/stylesheet/pages/_signin.scss
  src/stylesheet/states/_all.scss
  src/stylesheet/states/_color.scss
  src/stylesheet/states/_text.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#30 [Feature] Save token to cookies
  package-lock.json
  package.json
  src/app/core/auth/containers/Login.tsx
  src/app/core/services/auth.service.ts
  src/app/shared/components/Toast.tsx
  src/assets/icons/ic-error.svg
  src/assets/icons/ic-success.svg
  src/assets/icons/ic-waring.svg
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_toast.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#29 [Feature] Save user info to LS and handle redirect
  package-lock.json
  package.json
  src/app/core/auth/containers/Login.tsx
  src/app/core/helpers/storageHelper.ts
  src/app/core/services/auth.service.ts
  src/app/shared/components/Header.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#33 [Task] Add loading and handle error
  src/app/core/auth/containers/Register.tsx
  src/app/shared/components/Spinner.tsx
  src/app/shared/components/index.tsx
  src/stylesheet/modules/_spinner.scss
  src/stylesheet/pages/_register.scss
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Task

#32 [Feature] Login
  package-lock.json
  package.json
  src/App.tsx
  src/app/app.middleware.ts
  src/app/app.reducers.ts
  src/app/assets/react.svg
  src/app/core/auth/Auth.tsx
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.middleware.ts
  src/app/core/auth/auth.reducers.ts
  src/app/core/auth/constants/types.ts
  src/app/core/auth/containers/Login.tsx
  src/app/core/auth/containers/Register.tsx
  src/app/core/helpers/authHelper.ts
  src/app/core/helpers/jwtHelper.ts
  src/app/core/helpers/reducer-factory.ts
  src/app/core/helpers/storageHelper.ts
  src/app/core/services/api.service.ts
  src/app/core/services/auth.service.ts
  src/app/shared/components/Header.tsx
  src/app/shared/components/InputGroup.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/Spinner.tsx
  src/app/shared/components/index.tsx
  src/assets/icons/ic-hide.svg
  src/assets/icons/ic-show.svg
  src/assets/images/post-img.jpg
  src/assets/images/signin-img.jpg
  src/config/endpoint.ts
  src/stylesheet/base/_variables.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_input-group.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/pages/_signin.scss
  src/stylesheet/states/_all.scss
  src/stylesheet/states/_color.scss
  src/stylesheet/states/_text.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#37 [Feature] Handle logout and config router for header
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.middleware.ts
  src/app/core/auth/auth.reducers.ts
  src/app/core/auth/constants/types.ts
  src/app/core/auth/containers/Login.tsx
  src/app/core/auth/containers/Register.tsx
  src/app/core/services/api.service.ts
  src/app/core/services/auth.service.ts
  src/app/core/services/authStorage.service.ts
  src/app/pages/user/containers/UserList.tsx
  src/app/pages/user/containers/Users.tsx
  src/app/shared/components/EmptyData.tsx
  src/app/shared/components/Header.tsx
  src/config/endpoint.ts
  src/stylesheet/modules/_toast.scss
  src/stylesheet/pages/_register.scss
  src/stylesheet/states/_all.scss
  src/stylesheet/states/_display.scss
  src/stylesheet/states/_flex.scss
  src/stylesheet/states/_state.scss
  src/stylesheet/states/_text.scss
  src/stylesheet/states/_visibility.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#38 [Bug] - Fix post card skeleton loader
  src/app/pages/home/containers/components/PublicPost.tsx
  src/app/shared/components/Footer.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/PostList.tsx
  src/stylesheet/layout/_footer.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Bug

#40 [Features] Logout went cookies expired
  src/app/core/auth/containers/Login.tsx
  src/app/core/auth/containers/Register.tsx
  src/app/core/helpers/jwtHelper.ts
  src/app/core/services/auth.service.ts
  src/app/pages/Page.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#39 [Deloyment] Config for deployment
  .gitignore
  src/app/shared/components/PostList.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#43 [Fix bug] - Fix validate date
  src/app/core/auth/containers/Register.tsx
  src/app/shared/utils/formatDate.ts
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Bug

#42 [Feature] - Update Register UI
  src/app/core/auth/containers/Register.tsx
  src/assets/images/register-cover.png
  src/stylesheet/pages/_register.scss
Labels: [Priority] 03 - Low, [Status] 03 - Review needed, [Type] Feature

#41 [Fix Bug] Fix header sticky
  src/app/core/auth/containers/Register.tsx
  src/app/shared/components/Header.tsx
  src/stylesheet/layout/_header.scss
  src/stylesheet/states/_all.scss
  src/stylesheet/states/_position.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Bug

#44 [Fix bug] Fix handle signout and redirect
  src/app/pages/Page.tsx
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Bug

#47 [Fix Bug] Can redirect to login from home page after login
  index.html
  src/app/app.route.ts
  src/app/core/modules/custom-router-dom/RouterOutlet.tsx
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Bug

#46 [Modify] Fix post card layout
  index.html
  src/app/pages/home/containers/components/PublicPost.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/PostList.tsx
  src/assets/icons/ic-comment.svg
  src/assets/icons/ic-unlike.svg
  src/stylesheet/base/_all.scss
  src/stylesheet/base/_base.scss
  src/stylesheet/base/_mixins.scss
  src/stylesheet/base/_variables.scss
  src/stylesheet/layout/_grid.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_post.scss
  src/stylesheet/pages/_home.scss
  src/stylesheet/states/_text.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task, [Status] 07 - Fixed

#45 [Modify] - Fix Header UI
  src/app/pages/home/containers/components/PublicPost.tsx
  src/app/shared/components/Header.tsx
  src/assets/images/logo.png
  src/stylesheet/layout/_header.scss
  src/stylesheet/modules/_button.scss
  src/stylesheet/pages/_home.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Bug

#49 [Fix bug] Cant login after logout
  src/app/core/modules/custom-router-dom/RouterOutlet.tsx
  src/app/shared/components/Header.tsx
Labels: [Priority] 01 - Urgent, [Status] 03 - Review needed, [Type] Bug

#50 [Modify] - Fix Register Ui
  src/app/core/auth/containers/Login.tsx
  src/app/core/auth/containers/Register.tsx
  src/app/shared/components/SelectGroup.tsx
  src/app/shared/components/index.tsx
  src/stylesheet/base/_variables.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_select-group.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/pages/_register.scss
  src/stylesheet/pages/_signin.scss
  src/stylesheet/pages/_signup.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task, [Status] 07 - Fixed

#53 [Task] - Add List Comments UI
  src/app/shared/components/Comment.tsx
  src/app/shared/components/ListComments.tsx
  src/stylesheet/base/_reset.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_comment.scss
  src/stylesheet/modules/_list-comments.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Task

#52 [UI] Create article detail UI, modify home article list grid and add sidebar
  src/app/core/modules/custom-router-dom/PrivateRoute.tsx
  src/app/pages/articles/containers/ArticleDetail.tsx
  src/app/pages/articles/containers/ArticleList.tsx
  src/app/pages/articles/containers/Articles.tsx
  src/app/pages/articles/containers/components/ArticleTagItem.tsx
  src/app/pages/articles/containers/components/ArticleTagList.tsx
  src/app/pages/home/containers/Home.tsx
  src/app/shared/components/Header.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/PostList.tsx
  src/app/shared/components/PostSkeleton.tsx
  src/app/shared/components/Sidebar.tsx
  src/app/shared/components/index.tsx
  src/assets/icons/ic-bookmark-highlight.svg
  src/assets/icons/ic-bookmark.svg
  src/assets/icons/ic-comment-highlight.svg
  src/assets/icons/ic-comment-normal.svg
  src/assets/icons/ic-like-highlight.svg
  src/assets/icons/ic-like-normal.svg
  src/config/endpoint.ts
  src/stylesheet/layout/_all.scss
  src/stylesheet/layout/_sidebar.scss
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_short-info.scss
  src/stylesheet/modules/_tooltip.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/pages/_articles.scss
  src/stylesheet/pages/_home.scss
  src/stylesheet/states/_all.scss
  src/stylesheet/states/_display.scss
  src/stylesheet/states/_position.scss
  src/stylesheet/states/_spacing.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#55 [Task] Call api get list comments
  src/app/pages/articles/article.routes.ts
  src/app/pages/articles/containers/ArticleDetail.tsx
  src/app/shared/components/Comment.tsx
  src/app/shared/components/ListComments.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/Sidebar.tsx
  src/stylesheet/modules/_comment.scss
  src/stylesheet/modules/_list-comments.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Task

#54 [Feature] Articles list by tag UI and handle API
  src/app/core/modules/custom-router-dom/PrivateRoute.tsx
  src/app/pages/articles/article.routes.ts
  src/app/pages/articles/containers/ArticleByTag.tsx
  src/app/pages/articles/containers/Articles.tsx
  src/app/shared/components/PostList.tsx
  src/assets/icons/ic-tag.svg
  src/stylesheet/modules/_icon.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/pages/_article.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Feature

#56 [PBI4][Modify] Modify sidebar
  src/app/pages/articles/containers/ArticleDetail.tsx
  src/app/shared/components/PopularPostSkeleton.tsx
  src/app/shared/components/Sidebar.tsx
  src/app/shared/components/index.tsx
  src/stylesheet/layout/_sidebar.scss
  src/stylesheet/modules/_post.scss
  src/stylesheet/modules/_short-info.scss
  src/stylesheet/pages/_articles.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task

#58 [Task] - Add User Profile UI
  src/app/pages/user/containers/UserDetail.tsx
  src/app/pages/user/containers/components/UserProfile.tsx
  src/assets/icons/ic-dob.svg
  src/assets/icons/ic-mail.svg
  src/assets/icons/ic-person.svg
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_button.scss
  src/stylesheet/modules/_icon.scss
  src/stylesheet/modules/_user-profile.scss
  src/stylesheet/pages/_all.scss
  src/stylesheet/pages/_user.scss
Labels: [Priority] 03 - Normal, [Status] 03 - Review needed, [Type] Task

#60 [PBI6][Feature] Create article card UI
  src/app/pages/articles/containers/ArticleList.tsx
  src/app/pages/home/containers/Home.tsx
  src/app/pages/home/containers/components/PublicPost.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/PostList.tsx
  src/stylesheet/modules/_all.scss
  src/stylesheet/modules/_personal-post.scss
  src/stylesheet/modules/_short-info.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Feature

#61 [Feature] Add comment input ui
  src/app/shared/components/Comment.tsx
  src/app/shared/components/ListComments.tsx
  src/stylesheet/modules/_comment.scss
Labels: [Priority] 02 - High, [Priority] 03 - Normal, [Type] Task

#59 [Task] Apply api get user info
  src/app/core/helpers/jwtHelper.ts
  src/app/pages/articles/containers/ArticleDetail.tsx
  src/app/pages/user/containers/UserDetail.tsx
  src/app/pages/user/containers/components/UserProfile.tsx
  src/app/shared/components/Post.tsx
  src/app/shared/components/PostList.tsx
  src/stylesheet/modules/_user-profile.scss
Labels: [Priority] 02 - High, [Status] 03 - Review needed, [Type] Task
